fetcher:
  timeframes: ['1h', '4h', '1d']
  data_limit: 200
  delay_between_requests: 0.2
  use_test_symbols: false     # 👈 set to true when testing
  test_symbols:
    - BTC/USDT
    - ETH/USDT
    - BNB/USDT
    - SOL/USDT
    - XRP/USDT
    - ADA/USDT
    - DOGE/USDT
    - LINK/USDT
    - AVAX/USDT
    - MATIC/USDT